version: "3.9"

services:
  delivery-service-storage:
    container_name: sds-storage
    image: postgres:14
    environment:
      POSTGRES_DB: "sds-storage"
      POSTGRES_USER: "sdsUSER"
      POSTGRES_PASSWORD: "pgPWDsdsUSER!"
    volumes:
      - pg-sds-storage-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin-sds:
    container_name: pgadmin-sds
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pwdPGADMIN"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pg-sds-storage-volume: