version: "3.9"

services:
  delivery-service-storage:
    container_name: sds-storage
    image: postgres:14
    environment:
      POSTGRES_DB: "sds-storage"
      POSTGRES_USER: "sdsUSER"
      POSTGRES_PASSWORD: "pgPWDsdsUSER!"
    volumes:
      - pg-sds-storage-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  pg-sds-storage-volume: