spring:
  application:
    name: delivery-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${SHELTER_DB_HOST}:${SHELTER_DB_PORT}/${SHELTER_DB_DATABASE}
    username: ${SHELTER_DB_USER}
    password: ${SHELTER_DB_PASS}
  flyway:
    baseline-on-migrate: false
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080